version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=123;Database=betterpricedb
    volumes:
      - ./app-data:/app/images 
    command: ["sh", "-c", "./wait-for-it.sh db:5432 -- dotnet ef database update && dotnet BetterPrice.dll"]
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=betterpricedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
