version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=admin;Password=123;Database=bp
    volumes:
      - ./app-data:/app/images 
    command: ["sh", "-c", "dotnet ef database update && dotnet BeeterPrice.dll"]  # Run migrations before starting the app- 
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=bp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
