// <auto-generated />
using System;
using BetterPrice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetterPrice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetterPrice.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("BetterPrice.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Grãos"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Massas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Óleos e Temperos"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Doces e Sobremesas"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Refrigerantes"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Sucos"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Águas e Isotônicos"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Shampoos e Condicionadores"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Sabonetes e Gel para Banho"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Escovas e Cremes Dentais"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Detergentes"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Desinfetantes"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Esponjas e Panos de Limpeza"
                        });
                });

            modelBuilder.Entity("BetterPrice.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Alimentos"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bebidas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Limpeza"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Higiene Pessoal"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Frios"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Congelados"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Padaria"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Frutas e Verduras"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Carnes"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Mercearia"
                        });
                });

            modelBuilder.Entity("BetterPrice.Entities.ItemPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean");

                    b.Property<int>("MercadoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Oferta")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("MercadoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPrecos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 10.99m,
                            ProdutoId = 1,
                            Valor = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 7.90m,
                            ProdutoId = 2,
                            Valor = 8.50m
                        },
                        new
                        {
                            Id = 3,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 2.90m,
                            ProdutoId = 3,
                            Valor = 3.40m
                        },
                        new
                        {
                            Id = 4,
                            Destaque = true,
                            MercadoId = 4,
                            Oferta = 6.50m,
                            ProdutoId = 4,
                            Valor = 7.80m
                        },
                        new
                        {
                            Id = 5,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 4.99m,
                            ProdutoId = 5,
                            Valor = 5.60m
                        },
                        new
                        {
                            Id = 6,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 5.99m,
                            ProdutoId = 6,
                            Valor = 6.99m
                        },
                        new
                        {
                            Id = 7,
                            Destaque = false,
                            MercadoId = 7,
                            Oferta = 8.50m,
                            ProdutoId = 7,
                            Valor = 9.90m
                        },
                        new
                        {
                            Id = 8,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 2.99m,
                            ProdutoId = 8,
                            Valor = 3.50m
                        },
                        new
                        {
                            Id = 9,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 1.99m,
                            ProdutoId = 9,
                            Valor = 2.30m
                        },
                        new
                        {
                            Id = 10,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 1.69m,
                            ProdutoId = 10,
                            Valor = 1.99m
                        },
                        new
                        {
                            Id = 11,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 12.50m,
                            ProdutoId = 11,
                            Valor = 15.00m
                        },
                        new
                        {
                            Id = 12,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 10.00m,
                            ProdutoId = 12,
                            Valor = 12.00m
                        },
                        new
                        {
                            Id = 13,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 16.00m,
                            ProdutoId = 13,
                            Valor = 18.00m
                        },
                        new
                        {
                            Id = 14,
                            Destaque = false,
                            MercadoId = 4,
                            Oferta = 3.99m,
                            ProdutoId = 14,
                            Valor = 4.50m
                        },
                        new
                        {
                            Id = 15,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 4.99m,
                            ProdutoId = 15,
                            Valor = 5.99m
                        },
                        new
                        {
                            Id = 16,
                            Destaque = true,
                            MercadoId = 6,
                            Oferta = 6.00m,
                            ProdutoId = 16,
                            Valor = 7.50m
                        },
                        new
                        {
                            Id = 17,
                            Destaque = false,
                            MercadoId = 7,
                            Oferta = 4.50m,
                            ProdutoId = 17,
                            Valor = 4.90m
                        },
                        new
                        {
                            Id = 18,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 5.50m,
                            ProdutoId = 18,
                            Valor = 6.20m
                        },
                        new
                        {
                            Id = 19,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 6.70m,
                            ProdutoId = 19,
                            Valor = 7.80m
                        },
                        new
                        {
                            Id = 20,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 8.99m,
                            ProdutoId = 20,
                            Valor = 10.00m
                        },
                        new
                        {
                            Id = 21,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 11.00m,
                            ProdutoId = 1,
                            Valor = 13.50m
                        },
                        new
                        {
                            Id = 22,
                            Destaque = true,
                            MercadoId = 3,
                            Oferta = 7.50m,
                            ProdutoId = 2,
                            Valor = 9.00m
                        },
                        new
                        {
                            Id = 23,
                            Destaque = false,
                            MercadoId = 4,
                            Oferta = 3.20m,
                            ProdutoId = 3,
                            Valor = 3.80m
                        },
                        new
                        {
                            Id = 24,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 7.10m,
                            ProdutoId = 4,
                            Valor = 8.30m
                        },
                        new
                        {
                            Id = 25,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 5.20m,
                            ProdutoId = 5,
                            Valor = 6.50m
                        },
                        new
                        {
                            Id = 26,
                            Destaque = false,
                            MercadoId = 7,
                            Oferta = 6.00m,
                            ProdutoId = 6,
                            Valor = 7.20m
                        },
                        new
                        {
                            Id = 27,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 8.90m,
                            ProdutoId = 7,
                            Valor = 10.10m
                        },
                        new
                        {
                            Id = 28,
                            Destaque = true,
                            MercadoId = 9,
                            Oferta = 3.50m,
                            ProdutoId = 8,
                            Valor = 4.10m
                        },
                        new
                        {
                            Id = 29,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 2.10m,
                            ProdutoId = 9,
                            Valor = 2.50m
                        },
                        new
                        {
                            Id = 30,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 1.60m,
                            ProdutoId = 10,
                            Valor = 1.90m
                        },
                        new
                        {
                            Id = 31,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 14.00m,
                            ProdutoId = 11,
                            Valor = 16.50m
                        },
                        new
                        {
                            Id = 32,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 11.80m,
                            ProdutoId = 12,
                            Valor = 13.20m
                        },
                        new
                        {
                            Id = 33,
                            Destaque = false,
                            MercadoId = 4,
                            Oferta = 17.00m,
                            ProdutoId = 13,
                            Valor = 19.50m
                        },
                        new
                        {
                            Id = 37,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 4.30m,
                            ProdutoId = 17,
                            Valor = 5.00m
                        },
                        new
                        {
                            Id = 38,
                            Destaque = true,
                            MercadoId = 9,
                            Oferta = 5.90m,
                            ProdutoId = 18,
                            Valor = 6.50m
                        },
                        new
                        {
                            Id = 39,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 6.50m,
                            ProdutoId = 19,
                            Valor = 8.00m
                        },
                        new
                        {
                            Id = 40,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 9.20m,
                            ProdutoId = 20,
                            Valor = 10.50m
                        },
                        new
                        {
                            Id = 41,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 12.50m,
                            ProdutoId = 1,
                            Valor = 14.00m
                        },
                        new
                        {
                            Id = 42,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 8.00m,
                            ProdutoId = 2,
                            Valor = 9.50m
                        },
                        new
                        {
                            Id = 44,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 6.50m,
                            ProdutoId = 4,
                            Valor = 8.00m
                        },
                        new
                        {
                            Id = 49,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 2.50m,
                            ProdutoId = 9,
                            Valor = 2.80m
                        },
                        new
                        {
                            Id = 50,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 2.00m,
                            ProdutoId = 10,
                            Valor = 2.20m
                        },
                        new
                        {
                            Id = 51,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 7.50m,
                            ProdutoId = 19,
                            Valor = 8.50m
                        },
                        new
                        {
                            Id = 52,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 12.00m,
                            ProdutoId = 12,
                            Valor = 13.90m
                        },
                        new
                        {
                            Id = 53,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 5.70m,
                            ProdutoId = 5,
                            Valor = 6.20m
                        },
                        new
                        {
                            Id = 54,
                            Destaque = true,
                            MercadoId = 4,
                            Oferta = 8.50m,
                            ProdutoId = 7,
                            Valor = 10.00m
                        },
                        new
                        {
                            Id = 55,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 10.90m,
                            ProdutoId = 1,
                            Valor = 12.30m
                        },
                        new
                        {
                            Id = 56,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 1.80m,
                            ProdutoId = 10,
                            Valor = 2.10m
                        },
                        new
                        {
                            Id = 57,
                            Destaque = true,
                            MercadoId = 7,
                            Oferta = 6.80m,
                            ProdutoId = 16,
                            Valor = 7.60m
                        },
                        new
                        {
                            Id = 59,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 3.50m,
                            ProdutoId = 8,
                            Valor = 4.00m
                        },
                        new
                        {
                            Id = 60,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 2.10m,
                            ProdutoId = 9,
                            Valor = 2.50m
                        },
                        new
                        {
                            Id = 61,
                            Destaque = false,
                            MercadoId = 1,
                            Oferta = 6.60m,
                            ProdutoId = 4,
                            Valor = 7.90m
                        },
                        new
                        {
                            Id = 62,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 13.00m,
                            ProdutoId = 11,
                            Valor = 15.10m
                        },
                        new
                        {
                            Id = 63,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 3.30m,
                            ProdutoId = 3,
                            Valor = 3.90m
                        },
                        new
                        {
                            Id = 64,
                            Destaque = false,
                            MercadoId = 4,
                            Oferta = 3.80m,
                            ProdutoId = 14,
                            Valor = 4.50m
                        },
                        new
                        {
                            Id = 69,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 6.50m,
                            ProdutoId = 6,
                            Valor = 7.30m
                        },
                        new
                        {
                            Id = 70,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 6.00m,
                            ProdutoId = 18,
                            Valor = 6.80m
                        },
                        new
                        {
                            Id = 72,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 13.20m,
                            ProdutoId = 12,
                            Valor = 14.80m
                        },
                        new
                        {
                            Id = 73,
                            Destaque = false,
                            MercadoId = 7,
                            Oferta = 2.10m,
                            ProdutoId = 10,
                            Valor = 2.30m
                        },
                        new
                        {
                            Id = 74,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 8.60m,
                            ProdutoId = 7,
                            Valor = 9.90m
                        },
                        new
                        {
                            Id = 75,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 5.20m,
                            ProdutoId = 5,
                            Valor = 6.00m
                        },
                        new
                        {
                            Id = 76,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 3.30m,
                            ProdutoId = 8,
                            Valor = 3.80m
                        },
                        new
                        {
                            Id = 78,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 2.00m,
                            ProdutoId = 9,
                            Valor = 2.20m
                        },
                        new
                        {
                            Id = 79,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 7.10m,
                            ProdutoId = 16,
                            Valor = 7.90m
                        },
                        new
                        {
                            Id = 81,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 16.00m,
                            ProdutoId = 13,
                            Valor = 18.50m
                        },
                        new
                        {
                            Id = 82,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 3.80m,
                            ProdutoId = 3,
                            Valor = 4.20m
                        },
                        new
                        {
                            Id = 83,
                            Destaque = false,
                            MercadoId = 7,
                            Oferta = 5.80m,
                            ProdutoId = 15,
                            Valor = 6.50m
                        },
                        new
                        {
                            Id = 89,
                            Destaque = false,
                            MercadoId = 4,
                            Oferta = 6.60m,
                            ProdutoId = 6,
                            Valor = 7.10m
                        },
                        new
                        {
                            Id = 90,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 4.20m,
                            ProdutoId = 14,
                            Valor = 4.80m
                        },
                        new
                        {
                            Id = 91,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 3.30m,
                            ProdutoId = 8,
                            Valor = 3.90m
                        },
                        new
                        {
                            Id = 92,
                            Destaque = false,
                            MercadoId = 7,
                            Oferta = 7.00m,
                            ProdutoId = 4,
                            Valor = 8.10m
                        },
                        new
                        {
                            Id = 93,
                            Destaque = false,
                            MercadoId = 8,
                            Oferta = 7.10m,
                            ProdutoId = 2,
                            Valor = 7.90m
                        },
                        new
                        {
                            Id = 94,
                            Destaque = false,
                            MercadoId = 9,
                            Oferta = 13.50m,
                            ProdutoId = 12,
                            Valor = 15.00m
                        },
                        new
                        {
                            Id = 95,
                            Destaque = false,
                            MercadoId = 10,
                            Oferta = 5.10m,
                            ProdutoId = 5,
                            Valor = 5.70m
                        },
                        new
                        {
                            Id = 96,
                            Destaque = false,
                            MercadoId = 2,
                            Oferta = 1.80m,
                            ProdutoId = 10,
                            Valor = 2.00m
                        },
                        new
                        {
                            Id = 97,
                            Destaque = false,
                            MercadoId = 3,
                            Oferta = 5.50m,
                            ProdutoId = 15,
                            Valor = 6.00m
                        },
                        new
                        {
                            Id = 98,
                            Destaque = true,
                            MercadoId = 4,
                            Oferta = 8.00m,
                            ProdutoId = 7,
                            Valor = 9.50m
                        },
                        new
                        {
                            Id = 99,
                            Destaque = false,
                            MercadoId = 5,
                            Oferta = 16.40m,
                            ProdutoId = 13,
                            Valor = 17.90m
                        },
                        new
                        {
                            Id = 100,
                            Destaque = false,
                            MercadoId = 6,
                            Oferta = 6.20m,
                            ProdutoId = 18,
                            Valor = 6.80m
                        });
                });

            modelBuilder.Entity("BetterPrice.Entities.Mercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mercados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destaque = true,
                            Endereco = "Rua das Palmeiras, 123, São Paulo, SP",
                            Nome = "Pão de Açúcar",
                            UrlImagem = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcTl6OrE1EUtntSDrM_xGQ_i79qJdq5dBq9g&s"
                        },
                        new
                        {
                            Id = 2,
                            Destaque = true,
                            Endereco = "Avenida Paulista, 500, São Paulo, SP",
                            Nome = "Carrefour",
                            UrlImagem = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF7y3UbeRtSKAlHHy5W0p-hejaCi9KihHCkA&s"
                        },
                        new
                        {
                            Id = 3,
                            Destaque = true,
                            Endereco = "Rua 25 de Março, 1010, São Paulo, SP",
                            Nome = "Extra",
                            UrlImagem = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOf-t-njVAeC0v0M2Xy5e4Kn9QND636ytb9A&s"
                        },
                        new
                        {
                            Id = 5,
                            Destaque = false,
                            Endereco = "Avenida do Estado, 9876, São Paulo, SP",
                            Nome = "Atacadão Spani",
                            UrlImagem = "https://example.com/atacadao.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Destaque = true,
                            Endereco = "Rua do Sabor, 3456, São Paulo, SP",
                            Nome = "Hipermercado Walmart",
                            UrlImagem = "https://pbs.twimg.com/profile_images/1539351712514842629/Mvtw8vAt_400x400.png"
                        },
                        new
                        {
                            Id = 8,
                            Destaque = false,
                            Endereco = "Avenida dos Três, 1234, São Paulo, SP",
                            Nome = "Roldão",
                            UrlImagem = "https://example.com/roldao.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Destaque = false,
                            Endereco = "Rua do Mercado, 4321, São Paulo, SP",
                            Nome = "Tesco",
                            UrlImagem = "https://example.com/tesco.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Destaque = false,
                            Endereco = "Avenida Principal, 6789, São Paulo, SP",
                            Nome = "Sonae",
                            UrlImagem = "https://example.com/sonae.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Destaque = true,
                            Endereco = "Avenida São João, 101, Campinas, SP",
                            Nome = "Covabra",
                            UrlImagem = "https://yt3.googleusercontent.com/WxxBjaJlFVe0-OiEbxrcQLCw1hiWKN4IosKxooYkKSKN1dhPvvGDk44MwoYJBo87cJpc7UDa3w=s900-c-k-c0x00ffffff-no-rj"
                        },
                        new
                        {
                            Id = 6,
                            Destaque = true,
                            Endereco = "Rua Rio Branco, 777, São João da Boa Vista, SP",
                            Nome = "Savenago",
                            UrlImagem = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCD1GIZZBPrq5vkGYaZwhD7E-iam-NeANTzw&s"
                        });
                });

            modelBuilder.Entity("BetterPrice.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DepartamentoId = 1,
                            Descricao = "Arroz integral de 5kg.",
                            EAN = "7891234560011",
                            Nome = "Arroz Integral",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            DepartamentoId = 1,
                            Descricao = "Feijão preto de 1kg.",
                            EAN = "7891234560022",
                            Nome = "Feijão Preto",
                            UrlImagem = "https://propao.agilecdn.com.br/4493_1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            DepartamentoId = 1,
                            Descricao = "Macarrão instantâneo de 80g.",
                            EAN = "7891234560033",
                            Nome = "Macarrão Instantâneo",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            DepartamentoId = 1,
                            Descricao = "Óleo de soja 900ml.",
                            EAN = "7891234560044",
                            Nome = "Óleo de Soja",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            DepartamentoId = 1,
                            Descricao = "Chocolate ao leite 200g.",
                            EAN = "7891234560055",
                            Nome = "Chocolate ao Leite",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 5,
                            DepartamentoId = 2,
                            Descricao = "Refrigerante de cola 2L.",
                            EAN = "7891234560066",
                            Nome = "Refrigerante de Cola",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 5,
                            DepartamentoId = 2,
                            Descricao = "Refrigerante de laranja 2L.",
                            EAN = "7891234560077",
                            Nome = "Refrigerante de Laranja",
                            UrlImagem = "https://coopsp.vtexassets.com/arquivos/ids/215362-800-auto?v=637919527220430000&width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 6,
                            DepartamentoId = 2,
                            Descricao = "Suco de uva integral 1L.",
                            EAN = "7891234560088",
                            Nome = "Suco de Uva",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 6,
                            DepartamentoId = 2,
                            Descricao = "Suco de laranja natural 1L.",
                            EAN = "7891234560099",
                            Nome = "Suco de Laranja",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 7,
                            DepartamentoId = 2,
                            Descricao = "Água mineral 500ml.",
                            EAN = "7891234560100",
                            Nome = "Água Mineral",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 8,
                            DepartamentoId = 3,
                            Descricao = "Shampoo anticaspa 200ml.",
                            EAN = "7891234560111",
                            Nome = "Shampoo Anticaspa",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 8,
                            DepartamentoId = 3,
                            Descricao = "Shampoo hidratante 200ml.",
                            EAN = "7891234560122",
                            Nome = "Shampoo Hidratante",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 8,
                            DepartamentoId = 3,
                            Descricao = "Condicionador fortalecedor 200ml.",
                            EAN = "7891234560133",
                            Nome = "Condicionador Fortalecedor",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 9,
                            DepartamentoId = 3,
                            Descricao = "Sabonete líquido 250ml.",
                            EAN = "7891234560144",
                            Nome = "Sabonete Líquido",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 10,
                            DepartamentoId = 3,
                            Descricao = "Escova dental macia.",
                            EAN = "7891234560155",
                            Nome = "Escova Dental",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 11,
                            DepartamentoId = 4,
                            Descricao = "Detergente neutro 500ml.",
                            EAN = "7891234560166",
                            Nome = "Detergente Neutro",
                            UrlImagem = "https://tb0932.vtexassets.com/arquivos/ids/162732-800-auto?v=637705337202370000&width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 11,
                            DepartamentoId = 4,
                            Descricao = "Detergente de coco 500ml.",
                            EAN = "7891234560177",
                            Nome = "Detergente de Coco",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 12,
                            DepartamentoId = 4,
                            Descricao = "Desinfetante floral 500ml.",
                            EAN = "7891234560188",
                            Nome = "Desinfetante Floral",
                            UrlImagem = "https://images.tcdn.com.br/img/img_prod/1213476/desinfetante_5_litros_guimaraes_floral_2655_1_ef004baff3bc763e9629435d6a8b1c0c.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 12,
                            DepartamentoId = 4,
                            Descricao = "Desinfetante de limão 500ml.",
                            EAN = "7891234560199",
                            Nome = "Desinfetante Limão",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 13,
                            DepartamentoId = 4,
                            Descricao = "Esponja de aço 3 unidades.",
                            EAN = "7891234560200",
                            Nome = "Esponja de Aço",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 1,
                            DepartamentoId = 1,
                            Descricao = "Arroz parboilizado 5kg.",
                            EAN = "7891234560211",
                            Nome = "Arroz Parboilizado",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 2,
                            DepartamentoId = 1,
                            Descricao = "Macarrão espaguete 500g.",
                            EAN = "7891234560222",
                            Nome = "Macarrão Espaguete",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 3,
                            DepartamentoId = 1,
                            Descricao = "Molho de tomate 340g.",
                            EAN = "7891234560233",
                            Nome = "Molho de Tomate",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 4,
                            DepartamentoId = 1,
                            Descricao = "Biscoito recheado 150g.",
                            EAN = "7891234560244",
                            Nome = "Biscoito Recheado",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 6,
                            DepartamentoId = 2,
                            Descricao = "Suco de abacaxi 1L.",
                            EAN = "7891234560255",
                            Nome = "Suco de Abacaxi",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 4,
                            DepartamentoId = 1,
                            Descricao = "Biscoito salgado 200g.",
                            EAN = "7891234560266",
                            Nome = "Biscoito Salgado",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 5,
                            DepartamentoId = 5,
                            Descricao = "Queijo prato fatiado 300g.",
                            EAN = "7891234560277",
                            Nome = "Queijo Prato",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 5,
                            DepartamentoId = 5,
                            Descricao = "Presunto fatiado 300g.",
                            EAN = "7891234560288",
                            Nome = "Presunto",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 5,
                            DepartamentoId = 5,
                            Descricao = "Mortadela fatiada 300g.",
                            EAN = "7891234560299",
                            Nome = "Mortadela",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 4,
                            DepartamentoId = 1,
                            Descricao = "Leite condensado 395g.",
                            EAN = "7891234560300",
                            Nome = "Leite Condensado",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 31,
                            CategoriaId = 9,
                            DepartamentoId = 3,
                            Descricao = "Sabonete em barra 90g.",
                            EAN = "7891234560311",
                            Nome = "Sabonete em Barra",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 9,
                            DepartamentoId = 3,
                            Descricao = "Sabonete de coco 90g.",
                            EAN = "7891234560322",
                            Nome = "Sabonete de Coco",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 33,
                            CategoriaId = 10,
                            DepartamentoId = 3,
                            Descricao = "Desodorante aerosol 150ml.",
                            EAN = "7891234560333",
                            Nome = "Desodorante Aerosol",
                            UrlImagem = "https://example.com/desodorante_aerosol.jpg"
                        },
                        new
                        {
                            Id = 34,
                            CategoriaId = 10,
                            DepartamentoId = 3,
                            Descricao = "Pasta de dente 90g.",
                            EAN = "7891234560344",
                            Nome = "Pasta de Dente",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 35,
                            CategoriaId = 12,
                            DepartamentoId = 4,
                            Descricao = "Amaciante floral 1L.",
                            EAN = "7891234560355",
                            Nome = "Amaciante Floral",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 36,
                            CategoriaId = 12,
                            DepartamentoId = 4,
                            Descricao = "Amaciante de limão 1L.",
                            EAN = "7891234560366",
                            Nome = "Amaciante Limão",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 37,
                            CategoriaId = 8,
                            DepartamentoId = 3,
                            Descricao = "Creme para pentear 300ml.",
                            EAN = "7891234560377",
                            Nome = "Creme para Pentear",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 38,
                            CategoriaId = 8,
                            DepartamentoId = 3,
                            Descricao = "Óleo capilar 100ml.",
                            EAN = "7891234560388",
                            Nome = "Óleo Capilar",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 39,
                            CategoriaId = 5,
                            DepartamentoId = 1,
                            Descricao = "Manteiga 200g.",
                            EAN = "7891234560399",
                            Nome = "Manteiga",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 40,
                            CategoriaId = 5,
                            DepartamentoId = 1,
                            Descricao = "Iogurte natural 400g.",
                            EAN = "7891234560400",
                            Nome = "Iogurte Natural",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 41,
                            CategoriaId = 7,
                            DepartamentoId = 2,
                            Descricao = "Água com gás 500ml.",
                            EAN = "7891234560411",
                            Nome = "Água com Gás",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 42,
                            CategoriaId = 7,
                            DepartamentoId = 2,
                            Descricao = "Água com limão 500ml.",
                            EAN = "7891234560422",
                            Nome = "Água com Limão",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 43,
                            CategoriaId = 12,
                            DepartamentoId = 4,
                            Descricao = "Desinfetante sanitário 500ml.",
                            EAN = "7891234560433",
                            Nome = "Desinfetante Sanitário",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 44,
                            CategoriaId = 13,
                            DepartamentoId = 4,
                            Descricao = "Desengordurante 500ml.",
                            EAN = "7891234560444",
                            Nome = "Desengordurante",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 45,
                            CategoriaId = 5,
                            DepartamentoId = 1,
                            Descricao = "Margarina 500g.",
                            EAN = "7891234560455",
                            Nome = "Margarina",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 46,
                            CategoriaId = 4,
                            DepartamentoId = 1,
                            Descricao = "Chocolate em pó 400g.",
                            EAN = "7891234560466",
                            Nome = "Chocolate em Pó",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 47,
                            CategoriaId = 4,
                            DepartamentoId = 1,
                            Descricao = "Bolacha cream cracker 200g.",
                            EAN = "7891234560477",
                            Nome = "Bolacha Cream Cracker",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 48,
                            CategoriaId = 3,
                            DepartamentoId = 1,
                            Descricao = "Pão de forma 500g.",
                            EAN = "7891234560488",
                            Nome = "Pão de Forma",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 49,
                            CategoriaId = 5,
                            DepartamentoId = 5,
                            Descricao = "Queijo mussarela fatiado 300g.",
                            EAN = "7891234560499",
                            Nome = "Queijo Mussarela",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        },
                        new
                        {
                            Id = 50,
                            CategoriaId = 6,
                            DepartamentoId = 2,
                            Descricao = "Suco de caju 1L.",
                            EAN = "7891234560500",
                            Nome = "Suco de Caju",
                            UrlImagem = "https://www.aquarelapapeis.com.br/arquivos/produto_sem_foto.gif"
                        });
                });

            modelBuilder.Entity("BetterPrice.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<int>("TipoAutenticacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BetterPrice.Entities.Carrinho", b =>
                {
                    b.HasOne("BetterPrice.Entities.Usuario", "Usuario")
                        .WithOne("Carrinho")
                        .HasForeignKey("BetterPrice.Entities.Carrinho", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BetterPrice.Entities.ItemPreco", b =>
                {
                    b.HasOne("BetterPrice.Entities.Carrinho", null)
                        .WithMany("Items")
                        .HasForeignKey("CarrinhoId");

                    b.HasOne("BetterPrice.Entities.Mercado", "Mercado")
                        .WithMany()
                        .HasForeignKey("MercadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterPrice.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mercado");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BetterPrice.Entities.Produto", b =>
                {
                    b.HasOne("BetterPrice.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterPrice.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("BetterPrice.Entities.Carrinho", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BetterPrice.Entities.Usuario", b =>
                {
                    b.Navigation("Carrinho")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
